[project]
name = "pynted"
version = "1.0.0"

description = "Vinted API library for Python"
authors = [
    {"name"= "theoelsti", "email"= "theolsti@domain.local"}
]
dependencies = [
    "requests >= 2.31.0"
]

[tool.poetry]
readme = "README.md"
repository = "https://github.com/theoelsti/pynted"