name: Code polish

on: [push, pull_request]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install isort black flake8 pylint
    - name: Check code formatting with isort
      run: isort . --check-only
    - name: Check code formatting with black
      run: black --check . --skip-string-normalization
    - name: Lint code with flake8
      run: flake8 .
    - name: Lint code with pylint
      run: find . -type f -name "*.py" | xargs pylint