name: Code polish

on: [push, pull_request]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install isort black flake8 pylint requests
    - name: Check code formatting with isort
      run: isort . --check-only --ensure-newline-before-comments
    - name: Check code formatting with black
      run: black --check . --skip-string-normalization
    - name: Lint code with flake8
      run: flake8 .
    - name: Lint code with pylint
      run: pylint --rcfile=.pylintrc pynted --fail-under=9
    - name: Check for security vulnerabilities
      run: pip install bandit && bandit -r pynted
    - name: Run tests
      run: python -m unittest discover -s tests -v